# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biaoguo_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
