# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-06 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biaoguo_api', '0002_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalprice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
