# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-25 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biaoguo_api', '0006_auto_20180725_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalprice',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
